modLoader="javafml"
loaderVersion="[25,)"
issueTrackerURL="https://github.com/The-Acronym-Coders/BASE/issues"

[[mods]]
    modId="base"
    version="${file.jarVersion}"
    displayName="BASE"
    authors="Jared, Lanse, SkySom, warlordjones"
    description='''
        Library for Handling all the Internals of  Brass Goggled Coders, Miner Arcana, and Team Acronym Coders
    '''